### ISSUE TITLE
Huge log spam if supported mods aren't installed

### ISSUE THREAD

**Issue by FewerFlaws** [Noaaan/MythicMetals#21]
There should be a config option to toggle support for other mods.  Right now I'm getting hundreds of lines of errors as it tries to load recipes of invalid types.  Here's the size of error that pops up for each recipe related to a mod I don't have:
```
[11:45:12] [main/ERROR]: Parsing error loading recipe mythicmetals:modrecipes/techreborn/grinder/starrite_dust_from_ore
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'techreborn:grinder'
	at net.minecraft.class_1863.method_17875(class_1863.java:122) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_1863.method_17720(class_1863.java:122) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:1958) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1808) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1748) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:407) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:317) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:259) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:345) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1068) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Noaaan** [comment]
What version of the mod are you using? This should be fixed in 0.9.8 and up

**Comment by FewerFlaws** [comment]
The latest one: 0.9.9 snapshot C.  I don't see any option in the config to toggle mod support.  Do I have to add this into config myself?

I've never used a previous version of Mythic Metals btw.

**Comment by Noaaan** [comment]
Can I have a full modlist? I am unable to reproduce this issue

**Comment by FewerFlaws** [comment]
Here is the modlist from the log:
Mods:
  [✔️] advancements-enlarger-0.2.3
  [✔️] advdebug-2.2.0
  [✔️] amecs-1.3.2+mc.1.16.3
  [✔️] antighost-1.16.4-fabric0.25.1-1.1.3
  [✔️] autoconfig1u-3.3.1
  [✔️] autoreconnect-1.1.0
  [✔️] backslot-1.1.8
  [✔️] bedrockify-0.2.1-1.16.2+
  [✔️] bedrockwaters-1.4.3+1.16.4
  [✔️] BetterCaves-fabric-1.16.2-1.0.3
  [✔️] betterdroppeditems-1.2.4-1.16.2
  [✔️] biome-makeover-1.16.4-1.2.5
  [✔️] blame-2.3.0
  [✔️] bloodparticles-fabric-mc1.16.4-1.1.1
  [✔️] Blur-2.0.0-1.16.2+fabric
  [✔️] CameraOverhaul-1.2.2-fabric-universal
  [✔️] Cardinal-Components-API-2.7.10
  [✔️] charm-fabric-1.16.4-2.2.2
  [✔️] charmonium-fabric-1.16.4-2.2.2
  [✔️] cleancut-mc1.16-2.1-fabric
  [✔️] cloth-api-1.4.9
  [✔️] CompactStatusEffects-1.2.3
  [✔️] config-2-4.8.3
  [✔️] custom-crosshair-mod-v1.0.4-fabric-mc1.16.4
  [✔️] custom-fog-1.3.1
  [✔️] DamageTilt-1.16-fabric-0.1.1
  [✔️] dark-loading-screen-1.5.0
  [✔️] darkness-mc116-1.6.58
  [✔️] dawn-1.6.1
  [✔️] DisableCustomWorldsAdvice-1.2
  [✔️] dynamic-fps-1.2.1
  [✔️] DynamicSoundFilters-1.1.3+1.16.2
  [✔️] fabric-api-0.29.3+1.16
  [✔️] fabric-chunkpregen-0.3.3
  [✔️] fabric-language-kotlin-1.4.21+build.1
  [✔️] fabriczero-0.2.0
  [✔️] fallingleaves-1.3
  [✔️] fastbench-2.3
  [✔️] fastfurnace-2.3
  [✔️] fatxporbs-0.0.9+1.16.4
  [✔️] FirstPersonMod-2.0.0-SNAPSHOT
  [✔️] grid-1.16.4-fabric0.25.1-1.6.3
  [✔️] i-am-very-smart-2.1.0+mc1.16.1
  [✔️] inventory-hotswap-1.16-1.1.1
  [✔️] item-model-fix-1.0.0
  [✔️] juke-fix-1.0.0
  [✔️] konkrete_fabric_1.1.0_MC_1.16.3-1.16.4
  [✔️] lambdynamiclights-fabric-1.3.2+1.16.4
  [✔️] lithium-fabric-mc1.16.4-0.6.0
  [✔️] modmenu-1.14.13+build.19
  [✔️] mostructures-1.0.1+mc.1.16.4
  [✔️] mousewheelie-1.6.2+mc1.16.4
  [✔️] mythicmetals-0.9.9-snapshot-C
  [✔️] nbtcrafting-2.0.3+mc1.16.4
  [✔️] NotEnoughAnimations-1.0.3
  [✔️] overworld-two-1.0.4
  [✔️] phosphor-fabric-mc1.16.3-0.7.0+build.10
  [✔️] polymorph-fabric-0.0.8-1.16.4
  [✔️] PresenceFootsteps-r29+1.16.4
  [✔️] randompatches-2.1.5-fabric
  [✔️] repurposed_structures-1.16.4-1.7.3
  [✔️] RoughlyEnoughItems-5.8.9
  [✔️] sep-1.16.2_7
  [✔️] Skin+Swapper+1.16.4
  [✔️] smoothboot-fabric-1.16.4-1.4.0
  [✔️] sodium-fabric-mc1.16.3-0.1.0
  [✔️] spark-fabric
  [✔️] terrestria-2.1.5+build.28
  [✔️] torohealth-1.16.4-fabric-4
  [✔️] traverse-3.1.0+build.15
  [✔️] unearthed-1.0.5
  [✔️] YungsApi-1.16.4-Fabric-1

I will attempt to reproduce this with a clean modlist shortly.

**Comment by FewerFlaws** [comment]
With only fabric API, cloth config, auto config updated, and mythic metals the huge spam goes away but I still see the error that follows.  I'm now going to try with traverse and terrestria installed.
```
[15:06:26] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Enchant Giver, Mythic Metals)
[15:06:27] [main/ERROR]: Couldn't load item tag c:harvest_scythes as it is missing following references: harvest_scythes:wooden_scythe (from Enchant Giver),harvest_scythes:stone_scythe (from Enchant Giver),harvest_scythes:iron_scythe (from Enchant Giver),harvest_scythes:golden_scythe (from Enchant Giver),harvest_scythes:diamond_scythe (from Enchant Giver),harvest_scythes:netherite_scythe (from Enchant Giver),harvest_scythes:vulcanite_scythe (from Enchant Giver),harvest_scythes:copper_scythe (from Enchant Giver),harvest_scythes:tin_scythe (from Enchant Giver),harvest_scythes:silver_scythe (from Enchant Giver),harvest_scythes:lead_scythe (from Enchant Giver),harvest_scythes:bronze_scythe (from Enchant Giver),harvest_scythes:steel_scythe (from Enchant Giver),harvest_scythes:electrum_scythe (from Enchant Giver),harvest_scythes:rose_gold_scythe (from Enchant Giver),harvest_scythes:sterling_silver_scythe (from Enchant Giver),harvest_scythes:fools_gold_scythe (from Enchant Giver),harvest_scythes:metite_scythe (from Enchant Giver),harvest_scythes:asterite_scythe (from Enchant Giver),harvest_scythes:stellum_scythe (from Enchant Giver),harvest_scythes:galaxium_scythe (from Enchant Giver),harvest_scythes:univite_scythe (from Enchant Giver),harvest_scythes:lunum_scythe (from Enchant Giver),harvest_scythes:meteoric_steel_scythe (from Enchant Giver),harvest_scythes:alexandrite_scythe (from Enchant Giver),harvest_scythes:amethyst_scythe (from Enchant Giver),harvest_scythes:carbonado_scythe (from Enchant Giver),harvest_scythes:citrine_scythe (from Enchant Giver),harvest_scythes:corundum_scythe (from Enchant Giver),harvest_scythes:emerald_scythe (from Enchant Giver),harvest_scythes:ruby_scythe (from Enchant Giver),harvest_scythes:sapphire_scythe (from Enchant Giver),harvest_scythes:topaz_scythe (from Enchant Giver),harvest_scythes:tourmaline_scythe (from Enchant Giver),harvest_scythes:adamantite_scythe (from Enchant Giver),harvest_scythes:aetherium_scythe (from Enchant Giver),harvest_scythes:aquarium_scythe (from Enchant Giver),harvest_scythes:argonium_scythe (from Enchant Giver),harvest_scythes:banglum_scythe (from Enchant Giver),harvest_scythes:brass_scythe (from Enchant Giver),harvest_scythes:carmot_scythe (from Enchant Giver),harvest_scythes:celestium_scythe (from Enchant Giver),harvest_scythes:discordium_scythe (from Enchant Giver),harvest_scythes:durasteel_scythe (from Enchant Giver),harvest_scythes:etherite_scythe (from Enchant Giver),harvest_scythes:kyber_scythe (from Enchant Giver),harvest_scythes:metallurgium_scythe (from Enchant Giver),harvest_scythes:midas_gold_scythe (from Enchant Giver),harvest_scythes:mythril_scythe (from Enchant Giver),harvest_scythes:orichalcum_scythe (from Enchant Giver),harvest_scythes:osmium_scythe (from Enchant Giver),harvest_scythes:prometheum_scythe (from Enchant Giver),harvest_scythes:platinum_scythe (from Enchant Giver),harvest_scythes:quadrillum_scythe (from Enchant Giver),harvest_scythes:quicksilver_scythe (from Enchant Giver),harvest_scythes:runite_scythe (from Enchant Giver),harvest_scythes:slowsilver_scythe (from Enchant Giver),harvest_scythes:starrite_scythe (from Enchant Giver),harvest_scythes:stormyx_scythe (from Enchant Giver),harvest_scythes:tantalite_scythe (from Enchant Giver),harvest_scythes:truesilver_scythe (from Enchant Giver),harvest_scythes:ur_scythe (from Enchant Giver),harvest_scythes:nether_ruby_scythe (from Enchant Giver),harvest_scythes:cincinnasite_scythe (from Enchant Giver),harvest_scythes:cincinnasite_scythe_diamond (from Enchant Giver),harvest_scythes:terminite_scythe (from Enchant Giver),harvest_scythes:aeternium_scythe (from Enchant Giver),harvest_scythes:pendorite_scythe (from Enchant Giver),harvest_scythes:diamold_scythe (from Enchant Giver),harvest_scythes:batet_scythe (from Enchant Giver),harvest_scythes:luss_scythe (from Enchant Giver),harvest_scythes:vuld_scythe (from Enchant Giver)
[15:06:27] [main/ERROR]: Parsing error loading recipe harvest_scythes:cincinnasite_scythe_diamond
com.google.gson.JsonSyntaxException: Unknown item 'harvest_scythes:cincinnasite_scythe'
	at net.minecraft.class_1856.method_17873(class_1856.java:165) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_1856.method_8107(class_1856.java:165) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:1958) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1808) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1752) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:298) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:238) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1071) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Noaaan** [comment]
Yeah, that is a known issue. Will be fixed in the next build

**Comment by FewerFlaws** [comment]
Still looking for the issue, but I've loaded some earlier stages in the modlist to narrow down the list.  The issue will be an interaction with one of these.  I'll keep looking:
```
BedrockWaters
Biome Makeover
Charm
Charmonium
Custom Fog
Falling Leaves
LambDynamicLights
Overworld Two
Repurposed Structures
Terrestria
Traverse
True Darkness
Unearthed [Fabric]
YUNG's Better Caves
Mo' Structures
Mythic Metals
```

**Comment by Noaaan** [comment]
I will look into these then, but I am out of time today. I will look into it tomorrow!

**Comment by FewerFlaws** [comment]
Yep, sounds good.  Have fun in classes =]

**Comment by FewerFlaws** [comment]
This issue is an interaction with Charm.  I suspect the automatic recipe unlocker, but I don't know what the best solution is.

**Comment by Noaaan** [comment]
Fixed on Charms end in https://github.com/svenhjol/Charm/commit/3c85afa79f2cb025c139ebb45deb71ea21824b18

**Comment by FewerFlaws** [comment]
Although Charm fixed this specific issue on their end it would also be appropriate to implement [LibCD](https://www.curseforge.com/minecraft/mc-mods/libcd) so that the recipes here are only loaded if their parent mods are loaded.
