### ISSUE TITLE
[1.20.1] Crash with Aether Redux

### ISSUE THREAD

**Issue by Starexify** [Noaaan/MythicMetals#229]
I try to run the mod with Connector and Forgified Fabric API, I know there are issues with them. But they worked together till now.
Maybe mod makers would know what happened:

Crash Log: https://pastebin.com/XUELhM3B
Latest log: [latest.log](https://github.com/Noaaan/MythicMetals/files/14527389/latest.log)

I used the latest version of Aether: Redux 2.0.1 and Mythic Metals 0.19.3

**Comment by Noaaan** [comment]
I have been looking into this crash as it was reported earlier from #228. Thank you for the logs, they contain a lot more useful info. I think I know what causes it and will look into fixing it

**Comment by Noaaan** [comment]
This should hopefully be fixed by next release. I will try to do some testing later in order to verify that this doesn't happen. What is the exact issue: that loot tables are broken? (No loot found in chests)

**Comment by unilock** [comment]
Will the fix be backported to 1.20.1?

**Comment by Noaaan** [comment]
Oh, right. This is a Sinytra-related issue. Yeah, I will have it backported this weekend

**Comment by Noaaan** [comment]
0.19.5 is now released for 1.20

**Comment by unilock** [comment]
The issue still occurs; I think [TableBonusLootConditionMixin](https://github.com/Noaaan/MythicMetals/blob/aa89edb6506e0f45075add29aa8a8dfc63066f0c/src/main/java/nourl/mythicmetals/mixin/TableBonusLootConditionMixin.java) needs a null check, too.

**Comment by Noaaan** [comment]
Seems to be correct, looking at 
 https://pastebin.com/mdT9NjG5 from the above mentioned issue.

**Comment by Noaaan** [comment]
@unilock Could you try out this jar once it finishes building? It should fix the issue:
https://github.com/Noaaan/MythicMetals/actions/runs/8315886570

**Comment by Noaaan** [comment]
I have tested this jar with Aether Redux 2.0.2-1.20.1 and can confirm the crashes above are now fixed. 
I struggled with getting the latest version (2.0.6-1.20.1) running as I experienced really strange [owo-lib-related](https://gist.github.com/Noaaan/2286916696460b1b91dbc9a2ff8dd99f) crashes, but after running the game with a few more versions/configurations I eventually got it running with the following list:
  [✔] aeroblender-1.20.1-1.0.1-neoforge
  [✔] aether-1.20.1-1.2.0-neoforge
  [✔] aether-redux-2.0.6-1.20.1-neoforge
  [✔] alloy-forgery-2.1.2+1.20
  [✔] cardinal-components-api-5.2.2
  [✔] Connector-1.0.0-beta.39+1.20.1
  [✔] ConnectorExtras-1.10.0+1.20.1
  [✔] fabric-api-0.92.0+1.11.3+1.20.1
  [✔] geckolib-forge-1.20.1-4.4.4
  [✔] mythicmetals-0.19.6+1.20.1
  [✔] owo-lib-0.11.2+1.20
  [✔] TerraBlender-forge-1.20.1-3.0.0.169

**Comment by unilock** [comment]
Sorry for the delay; I can test that build soon, but given you did pretty much exactly what I did in a private build (that works fine), I'm fairly certain the issue is fixed now.

As for the owo-lib crash: make sure you're running with Forge 47.1.3 *specifically,* or the latest version of NeoForge, and try Connector v1.0.0-beta.37 - I've had some issues of my own with the latest betas.

**Comment by Noaaan** [comment]
I do suspect this being related to Connector, as I combed through the code and everything seemed fine. It is weird that activating Redux specifically in my test instance triggered the issue. 
I was actually using Forge 47.1.3 as well. Not sure why it appeared and disappeared `¯\_(ツ)_/¯`

**Comment by Noaaan** [comment]
Should be fixed in the release of 0.19.6
